-- ============================================================
-- Email/password signup support
-- Migration: 005_email_signup.sql
-- ============================================================

-- phone_number was NOT NULL (Telegram-only signup). Email/password
-- users won't have one, so it needs to become optional.
ALTER TABLE users ALTER COLUMN phone_number DROP NOT NULL;

ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS dob DATE NULL;

-- `username` already existed (unused) — repurposed as the autogenerated
-- unique user ID (e.g. "HVB_2108"). `email` already existed too.
CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique
    ON users (email) WHERE email IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS users_username_unique
    ON users (username) WHERE username IS NOT NULL;
